language: c++
sudo: false

matrix:
  include:
    - env: >
        COMPILER=clang++-3.8 STDLIB=libc++
        CONFIGURATION=Debug  SLOW=true
        FLAGS="-fsanitize=address -fsanitize=leak"
      addons: &clang38
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages: clang-3.8

    - env: >
        COMPILER=clang++-3.8  STDLIB=libc++
        CONFIGURATION=Release SLOW=false
        BENCHMARK=true
      addons: *clang38

    - env: >
        COMPILER=g++-6
        CONFIGURATION=Debug SLOW=true
        COVERAGE=true
      addons: &gcc6
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6

    - env: >
        COMPILER=g++-6
        CONFIGURATION=Release SLOW=false
        BENCHMARK=true DOCS=true
      addons: *gcc6

cache:
  - pip
  - ccache
  - directories:
      - ${TRAVIS_BUILD_DIR}/build/deps
      - ${TRAVIS_BUILD_DIR}/deps

before_install: source tools/travis/all.bash && travis-before-install
install:        travis-install
before_script:  travis-before-script
script:         travis-script
after_success:  travis-after-success
